[package]
authors = ["user"]
edition = "2018"
name = "encoder"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = {version = "0.4", features = ["rand"]}
num-traits = "0.2"
rand = "0.8.0"
clap = "2.33.3"